=== mkalme/datubazes_4_darbs_3_kurss_ditf/data/university.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="universitate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fakultate" type="fakultateType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="fakultateType">
        <xs:sequence>
            <xs:element name="studiju_programma" type="studijuProgrammaType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="nosaukums" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="studijuProgrammaType">
        <xs:sequence>
            <xs:element name="studiju_kurss" type="studijuKurssType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="nosaukums" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="studijuKurssType">
        <xs:sequence>
            <xs:element name="modulis" type="modulisType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="nosaukums" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="modulisType">
        <xs:sequence>
            <xs:element name="temats" type="tematsType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="nosaukums" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="tematsType">
        <xs:sequence>
            <xs:element name="apraksts" type="xs:string"/>
            <xs:element name="kreditpunkti" type="kreditpunktiType"/>
            <xs:element name="stundu_skaits" type="stunduSkaitsType"/>
        </xs:sequence>
        <xs:attribute name="nosaukums" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="kreditpunktiType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="stunduSkaitsType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="16"/>
            <xs:maxInclusive value="320"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== mkalme/datubazes_4_darbs_3_kurss_ditf/data/university.xml
<?xml version="1.0" encoding="UTF-8"?>
<universitate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="university.xsd">
    
    <fakultate nosaukums="Datorikas fakultate">
        <studiju_programma nosaukums="Datorzinatnes">
            <studiju_kurss nosaukums="Datu bazes">
                <modulis nosaukums="Relaciju datu bazes">
                    <temats nosaukums="SQL valoda">
                        <apraksts>SQL vaicajumu veidosana un optimizacija</apraksts>
                        <kreditpunkti>2</kreditpunkti>
                        <stundu_skaits>32</stundu_skaits>
                    </temats>
                    <temats nosaukums="Indeksesana">
                        <apraksts>Datu bazu indeksu izveide un pielietosana</apraksts>
                        <kreditpunkti>1</kreditpunkti>
                        <stundu_skaits>16</stundu_skaits>
                    </temats>
                </modulis>
                <modulis nosaukums="NoSQL datu bazes">
                    <temats nosaukums="MongoDB">
                        <apraksts>MongoDB datu bazes pamati</apraksts>
                        <kreditpunkti>1</kreditpunkti>
                        <stundu_skaits>16</stundu_skaits>
                    </temats>
                </modulis>
            </studiju_kurss>
            <studiju_kurss nosaukums="Programmesana">
                <modulis nosaukums="Java programmesana">
                    <temats nosaukums="Objektorienteta programmesana">
                        <apraksts>OOP koncepti Java valoda</apraksts>
                        <kreditpunkti>3</kreditpunkti>
                        <stundu_skaits>48</stundu_skaits>
                    </temats>
                    <temats nosaukums="Pavedienu programmesana">
                        <apraksts>Pavedieni</apraksts>
                        <kreditpunkti>2</kreditpunkti>
                        <stundu_skaits>32</stundu_skaits>
                    </temats>
                </modulis>
            </studiju_kurss>
        </studiju_programma>
    </fakultate>
</universitate>
